experimentName: xgboost_tuning
trialConcurrency: 18
maxTrialNumber: 3600
trainingService:
  platform: local
searchSpaceFile: search_space_xgboost5.json
tuner:
  name: TPE
  classArgs:
    optimize_mode: minimize
trialCommand: python3 train_nni.py --filepath output/dataforxgboost.csv --target_column VisitDuration --exp_dir nni10_explog --groupingparams groupingsetting.yml
trialCodeDirectory: .
experimentWorkingDirectory: nni10_explog