nni:
  exp_stp: 'nni10_explog'
  best_exp_id: 
  sequence_id: 
train:
  filepath: 'output/dataforxgboost.csv'
  target_column: 'VisitDuration'
  feature_list: 'boruta_explog/e2f721e9/top25_confirmed_vars.txt'
  grouping_parameter_id: '1'
  groupingparams: 
    bins: [0, 2, 6, 12, 25, 55, 150]
    labels: ['0-2', '2-6', '6-12', '12-25', '25-55', '55+']
  label_toTrain: ['all']

